# Generated by Django 5.0.7 on 2024-07-26 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_unit_ingredientquantity_alter_recipe_ingredients_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DietaryRestriction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='Allergen',
        ),
        migrations.AlterField(
            model_name='recipe',
            name='allergens',
            field=models.ManyToManyField(blank=True, to='recipes.dietaryrestriction'),
        ),
    ]
