# Generated by Django 5.0.7 on 2024-07-26 05:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_dietaryrestriction_delete_allergen_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='allergens',
            new_name='Dietary_Restrictions',
        ),
    ]
