# Generated by Django 5.0.7 on 2024-07-21 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='type_of_treat',
        ),
    ]
