# Generated by Django 5.0.7 on 2024-07-21 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_remove_recipe_type_of_treat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='allergen',
            name='recipe',
        ),
    ]
