# Generated by Django 5.0.7 on 2024-07-21 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_remove_allergen_recipe'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='ingredients',
            field=models.CharField(default='null', max_length=300),
            preserve_default=False,
        ),
    ]
