# Generated by Django 5.0.7 on 2024-07-26 05:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_rename_allergens_recipe_dietary_restrictions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unit',
            name='name',
        ),
    ]
