# Generated by Django 5.0.7 on 2024-07-28 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_remove_unit_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='Dietary_Restrictions',
        ),
        migrations.AddField(
            model_name='recipe',
            name='dietary_restrictions',
            field=models.ManyToManyField(blank=True, to='recipes.dietaryrestriction'),
        ),
    ]
